// SPDX-License-Identifier: MIT

use std::collections::{BTreeMap, BTreeSet};

use sts2_harness::{
    LegalDestination, MapCompleteness, MapEdge, MapGraphError, MapNode, MapNodeStatus,
    ValidatedMapGraph,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OracleNode {
    pub id: String,
    pub row: i32,
    pub column: i32,
    pub category: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OracleDestination {
    pub node_id: String,
    pub action_id: String,
}

/// A fixture-owned graph description. These are original deterministic synthetic fixtures
/// generated by this test support module, with no game assets or imported reference source.
/// Their topology and expected values are calculated here without calling the harness analysis
/// implementation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OracleFixture {
    pub snapshot_digest: String,
    pub map_instance: String,
    pub act: String,
    pub source_state_id: String,
    pub generation: u64,
    pub completeness: MapCompleteness,
    pub nodes: Vec<OracleNode>,
    pub edges: Vec<(String, String)>,
    pub current_node: Option<String>,
    pub legal_destinations: Vec<OracleDestination>,
    pub terminals: Vec<String>,
}

impl OracleFixture {
    pub fn from_parts(
        map_instance: &str,
        nodes: &[(&str, i32, i32, &str)],
        edges: &[(&str, &str)],
        current_node: Option<&str>,
        legal_destinations: &[(&str, &str)],
        terminals: &[&str],
        completeness: MapCompleteness,
    ) -> Self {
        Self {
            snapshot_digest: digest_for(map_instance),
            map_instance: map_instance.to_owned(),
            act: "act-1".to_owned(),
            source_state_id: format!("state-{map_instance}"),
            generation: 7,
            completeness,
            nodes: nodes
                .iter()
                .map(|(id, row, column, category)| OracleNode {
                    id: (*id).to_owned(),
                    row: *row,
                    column: *column,
                    category: (*category).to_owned(),
                })
                .collect(),
            edges: edges
                .iter()
                .map(|(from, to)| ((*from).to_owned(), (*to).to_owned()))
                .collect(),
            current_node: current_node.map(str::to_owned),
            legal_destinations: legal_destinations
                .iter()
                .map(|(node_id, action_id)| OracleDestination {
                    node_id: (*node_id).to_owned(),
                    action_id: (*action_id).to_owned(),
                })
                .collect(),
            terminals: terminals.iter().map(|id| (*id).to_owned()).collect(),
        }
    }

    pub fn to_validated_graph(&self) -> Result<ValidatedMapGraph, MapGraphError> {
        ValidatedMapGraph::new(
            self.snapshot_digest.clone(),
            self.map_instance.clone(),
            self.act.clone(),
            self.source_state_id.clone(),
            self.generation,
            self.completeness.clone(),
            self.nodes
                .iter()
                .map(|node| MapNode {
                    node_id: node.id.clone(),
                    row: node.row,
                    column: node.column,
                    category: node.category.clone(),
                    status: MapNodeStatus::Unknown,
                })
                .collect(),
            self.edges
                .iter()
                .map(|(from, to)| MapEdge {
                    from: from.clone(),
                    to: to.clone(),
                })
                .collect(),
            self.current_node.clone(),
            self.legal_destinations
                .iter()
                .map(|destination| LegalDestination {
                    node_id: destination.node_id.clone(),
                    action_id: destination.action_id.clone(),
                })
                .collect(),
            self.terminals.clone(),
        )
    }

    pub fn node_ids(&self) -> BTreeSet<String> {
        self.nodes.iter().map(|node| node.id.clone()).collect()
    }

    pub fn edge_set(&self) -> BTreeSet<(String, String)> {
        self.edges.iter().cloned().collect()
    }

    pub fn outgoing(&self) -> BTreeMap<String, Vec<String>> {
        let mut result = self
            .node_ids()
            .into_iter()
            .map(|id| (id, Vec::new()))
            .collect::<BTreeMap<_, _>>();
        for (from, to) in &self.edges {
            if let Some(children) = result.get_mut(from) {
                children.push(to.clone());
            }
        }
        for children in result.values_mut() {
            children.sort();
        }
        result
    }

    pub fn topological_order(&self) -> Result<Vec<String>, String> {
        let outgoing = self.outgoing();
        let mut indegree = self
            .node_ids()
            .into_iter()
            .map(|id| (id, 0_usize))
            .collect::<BTreeMap<_, _>>();
        for children in outgoing.values() {
            for child in children {
                if let Some(value) = indegree.get_mut(child) {
                    *value += 1;
                }
            }
        }
        let mut ready = indegree
            .iter()
            .filter_map(|(id, degree)| (*degree == 0).then_some(id.clone()))
            .collect::<BTreeSet<_>>();
        let mut order = Vec::with_capacity(indegree.len());
        while let Some(id) = ready.pop_first() {
            order.push(id.clone());
            if let Some(children) = outgoing.get(&id) {
                for child in children {
                    if let Some(degree) = indegree.get_mut(child) {
                        *degree -= 1;
                        if *degree == 0 {
                            ready.insert(child.clone());
                        }
                    }
                }
            }
        }
        if order.len() == indegree.len() {
            Ok(order)
        } else {
            Err("fixture is cyclic".to_owned())
        }
    }

    /// Independent reverse-DP oracle: each terminal is evaluated separately, so callers can
    /// inspect both the current source and every legal destination without route enumeration.
    pub fn reverse_path_counts(&self, source: &str) -> Result<BTreeMap<String, u128>, String> {
        let order = self.topological_order()?;
        let outgoing = self.outgoing();
        let terminals = self.terminals.iter().cloned().collect::<BTreeSet<_>>();
        let mut result = BTreeMap::new();
        for terminal in &self.terminals {
            let mut counts = self
                .node_ids()
                .into_iter()
                .map(|id| (id, 0_u128))
                .collect::<BTreeMap<_, _>>();
            for id in order.iter().rev() {
                if id == terminal {
                    counts.insert(id.clone(), 1);
                } else if terminals.contains(id) {
                    counts.insert(id.clone(), 0);
                } else {
                    let total = outgoing
                        .get(id)
                        .into_iter()
                        .flatten()
                        .map(|child| counts.get(child).copied().unwrap_or(0))
                        .sum();
                    counts.insert(id.clone(), total);
                }
            }
            result.insert(terminal.clone(), counts.get(source).copied().unwrap_or(0));
        }
        Ok(result)
    }

    /// Exhaustive enumeration is intentionally available only to small fixture tests.
    pub fn all_paths_from(&self, source: &str) -> Result<Vec<Vec<String>>, String> {
        self.topological_order()?;
        let mut paths = Vec::new();
        let mut path = vec![source.to_owned()];
        let terminals = self.terminals.iter().cloned().collect::<BTreeSet<_>>();
        self.enumerate(source, &terminals, &mut path, &mut paths);
        Ok(paths)
    }

    pub fn legal_paths(&self) -> Result<BTreeMap<String, Vec<Vec<String>>>, String> {
        self.topological_order()?;
        let mut result = BTreeMap::new();
        for destination in &self.legal_destinations {
            let suffixes = self.all_paths_from(&destination.node_id)?;
            let routes = suffixes
                .into_iter()
                .map(|suffix| {
                    self.current_node
                        .as_ref()
                        .map_or(suffix.clone(), |current| {
                            let mut route = vec![current.clone()];
                            route.extend(suffix);
                            route
                        })
                })
                .collect::<Vec<_>>();
            result.insert(destination.action_id.clone(), routes);
        }
        Ok(result)
    }

    fn enumerate(
        &self,
        node: &str,
        terminals: &BTreeSet<String>,
        path: &mut Vec<String>,
        paths: &mut Vec<Vec<String>>,
    ) {
        if terminals.contains(node) {
            paths.push(path.clone());
            return;
        }
        if let Some(children) = self.outgoing().get(node) {
            for child in children {
                path.push(child.clone());
                self.enumerate(child, terminals, path, paths);
                path.pop();
            }
        }
    }

    pub fn route_is_concrete(&self, route: &[String]) -> bool {
        let Some(last) = route.last() else {
            return false;
        };
        if let Some(current) = &self.current_node
            && route.first() != Some(current)
        {
            return false;
        }
        if !self.terminals.iter().any(|terminal| terminal == last) {
            return false;
        }
        let required = route
            .windows(2)
            .map(|pair| (pair[0].clone(), pair[1].clone()))
            .collect::<BTreeSet<_>>();
        self.edge_set().is_superset(&required)
    }
}

pub fn digest_for(map_instance: &str) -> String {
    let bytes = map_instance.as_bytes();
    let mut state = 0xcbf29ce484222325_u64;
    for byte in bytes {
        state ^= u64::from(*byte);
        state = state.wrapping_mul(0x100000001b3);
    }
    let alphabet = b"0123456789abcdef";
    (0..64)
        .map(|index| {
            let input = bytes.get(index % bytes.len().max(1)).copied().unwrap_or(0);
            state = state.rotate_left(5).wrapping_add(u64::from(input));
            alphabet[(state as usize) & 0x0f] as char
        })
        .collect()
}

pub fn crossed_branch_fixture(map_instance: &str, labels: (&str, &str)) -> OracleFixture {
    OracleFixture::from_parts(
        map_instance,
        &[
            ("start", 0, 0, "start"),
            ("left", 1, 0, labels.0),
            ("right", 1, 0, labels.1),
            ("merge", 2, 0, "event"),
            ("terminal-a", 3, -1, "terminal"),
            ("terminal-b", 3, 1, "terminal"),
            ("orphan", 1, 2, "unknown"),
        ],
        &[
            ("right", "merge"),
            ("start", "right"),
            ("left", "terminal-b"),
            ("merge", "terminal-b"),
            ("start", "left"),
            ("merge", "terminal-a"),
            ("right", "terminal-a"),
            ("left", "merge"),
        ],
        Some("start"),
        &[("left", "action-left"), ("right", "action-right")],
        &["terminal-a", "terminal-b"],
        MapCompleteness::Complete,
    )
}

pub fn layered_fixture(layers: usize, map_instance: &str) -> OracleFixture {
    let mut nodes = vec![("start".to_owned(), 0, 0, "start".to_owned())];
    for layer in 0..layers {
        nodes.push((
            format!("layer-{layer}-a"),
            i32::try_from(layer + 1).unwrap_or(i32::MAX),
            0,
            "unknown".to_owned(),
        ));
        nodes.push((
            format!("layer-{layer}-b"),
            i32::try_from(layer + 1).unwrap_or(i32::MAX),
            1,
            "unknown".to_owned(),
        ));
    }
    nodes.push((
        "goal".to_owned(),
        i32::try_from(layers + 1).unwrap_or(i32::MAX),
        0,
        "boss".to_owned(),
    ));
    let mut edges = Vec::new();
    if layers == 0 {
        edges.push(("start".to_owned(), "goal".to_owned()));
    } else {
        edges.push(("start".to_owned(), "layer-0-a".to_owned()));
        edges.push(("start".to_owned(), "layer-0-b".to_owned()));
        for layer in 0..layers.saturating_sub(1) {
            for from in ["a", "b"] {
                for to in ["a", "b"] {
                    edges.push((
                        format!("layer-{layer}-{from}"),
                        format!("layer-{}-{to}", layer + 1),
                    ));
                }
            }
        }
        edges.push((format!("layer-{}-a", layers - 1), "goal".to_owned()));
        edges.push((format!("layer-{}-b", layers - 1), "goal".to_owned()));
    }
    let node_refs = nodes
        .iter()
        .map(|(id, row, column, category)| (id.as_str(), *row, *column, category.as_str()))
        .collect::<Vec<_>>();
    let edge_refs = edges
        .iter()
        .map(|(from, to)| (from.as_str(), to.as_str()))
        .collect::<Vec<_>>();
    let first_a = if layers == 0 { "goal" } else { "layer-0-a" };
    let first_b = if layers == 0 { "goal" } else { "layer-0-b" };
    OracleFixture::from_parts(
        map_instance,
        &node_refs,
        &edge_refs,
        Some("start"),
        &[(first_a, "action-a"), (first_b, "action-b")],
        &["goal"],
        MapCompleteness::Complete,
    )
}

pub fn cycle_fixture() -> OracleFixture {
    OracleFixture::from_parts(
        "cycle-run",
        &[("a", 0, 0, "event"), ("b", 1, 0, "event")],
        &[("a", "b"), ("b", "a")],
        Some("a"),
        &[("b", "action-b")],
        &["b"],
        MapCompleteness::Complete,
    )
}

pub fn prestart_fixture() -> OracleFixture {
    OracleFixture::from_parts(
        "prestart-run",
        &[("start", 0, 0, "start"), ("terminal", 1, 0, "boss")],
        &[("start", "terminal")],
        None,
        &[],
        &["terminal"],
        MapCompleteness::Complete,
    )
}

pub fn incomplete_fixture() -> OracleFixture {
    let mut fixture = crossed_branch_fixture("incomplete-run", ("shop", "rest"));
    fixture.completeness = MapCompleteness::Incomplete;
    fixture
}

pub fn unbound_legal_destination_fixture() -> OracleFixture {
    OracleFixture::from_parts(
        "special-move-run",
        &[
            ("start", 0, 0, "start"),
            ("special", 1, 4, "unknown"),
            ("goal", 2, 4, "boss"),
        ],
        &[("special", "goal")],
        Some("start"),
        &[("special", "action-special")],
        &["goal"],
        MapCompleteness::Complete,
    )
}
