// SPDX-License-Identifier: MIT

const CHECKSUM_FILES: &[(&str, &[u8])] = &[
    (
        "../../conformance/cases/runtime-v4-expert-rest-action-v1.json",
        CONFORMANCE_BYTES,
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-empty-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-empty-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-unknown-action-kind.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-unknown-action-kind.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-unrelated-option-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-accepted-unrelated-option-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-evidence-hp-change.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-evidence-hp-change.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-evidence-native-completion.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-evidence-native-completion.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-heal-noop.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-heal-noop.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-unrelated-option-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-unrelated-option-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-untested-option-witness.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-completed-untested-option-witness.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-absent-player.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-absent-player.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-evidence-hp-change.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-evidence-hp-change.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-evidence-native-completion.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-mend-selection-completed-evidence-native-completion.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-bogus.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-bogus.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-duplicates.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-duplicates.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-required-count-1.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-required-count-1.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-selection-kind-player.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-selection-kind-player.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-unrelated-selection-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-completed-unrelated-selection-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-remaining-count-99.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-remaining-count-99.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-unlisted-choice.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-unlisted-choice.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-unrelated-selection-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-progressed-unrelated-selection-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-no-choice-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-no-choice-action.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-option-kind-mismatch.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-option-kind-mismatch.json"
        ),
    ),
    (
        "../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-unrelated-selection-action.json",
        include_bytes!(
            "../../../conformance/mutations/runtime-v4-expert-rest-action-v1/action-selection-requested-unrelated-selection-action.json"
        ),
    ),
    (
        "../../schemas/runtime-v4-expert-rest-action-v1.schema.json",
        SOURCE_SCHEMA_BYTES,
    ),
    ("manifest.json", MANIFEST_BYTES),
    ("schema.json", SCHEMA_BYTES),
    (
        "golden/action-accepted.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-accepted.json"
        ),
    ),
    (
        "golden/action-completed.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-completed.json"
        ),
    ),
    (
        "golden/action-mend-selection-completed.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-mend-selection-completed.json"
        ),
    ),
    (
        "golden/action-mend-selection-requested.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-mend-selection-requested.json"
        ),
    ),
    (
        "golden/action-rejected.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-rejected.json"
        ),
    ),
    (
        "golden/action-request.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-request.json"
        ),
    ),
    (
        "golden/action-selection-completed.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-completed.json"
        ),
    ),
    (
        "golden/action-selection-confirm-request.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-confirm-request.json"
        ),
    ),
    (
        "golden/action-selection-early-confirm-rejected.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-early-confirm-rejected.json"
        ),
    ),
    (
        "golden/action-selection-first-request.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-first-request.json"
        ),
    ),
    (
        "golden/action-selection-option-request.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-option-request.json"
        ),
    ),
    (
        "golden/action-selection-progressed.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-progressed.json"
        ),
    ),
    (
        "golden/action-selection-requested.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-requested.json"
        ),
    ),
    (
        "golden/action-selection-second-progressed.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-second-progressed.json"
        ),
    ),
    (
        "golden/action-selection-second-request.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-selection-second-request.json"
        ),
    ),
    (
        "golden/action-unknown.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/golden/action-unknown.json"
        ),
    ),
    (
        "producer/mend-selection-lifecycle.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/producer/mend-selection-lifecycle.json"
        ),
    ),
    (
        "producer/smith-selection-lifecycle.json",
        include_bytes!(
            "../../../protocol-artifact/runtime-v4-expert-rest-action/producer/smith-selection-lifecycle.json"
        ),
    ),
];
